PROJ_HOME=d:\program\code/json
INCL=${PROJ_HOME}/incl

OBJ_LIST= util.o json_object.o json_string.o main.o json_file.o json_array.o

CC=gcc
CFLAGS= -g -c


all: jsont

.c.o:
	${CC} ${CFLAGS} -I${INCL} $*.c

jsont: ${OBJ_LIST}
	${CC} $^ -o $@

co:
	rm -f *.o
